# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# compile C with C:/msys64/mingw64/bin/cc.exe
# compile CXX with C:/msys64/mingw64/bin/c++.exe
C_DEFINES = -DBX_CONFIG_ENABLE_MSVC_LEVEL4_WARNINGS=1 -DGLEW_STATIC -DIMGUI_DISABLE_OBSOLETE_FUNCTIONS -DUSE_DL_PREFIX -D_CRT_SECURE_NO_WARNINGS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS

C_INCLUDES = @CMakeFiles/PathTracer.dir/includes_C.rsp

C_FLAGS = 

CXX_DEFINES = -DBX_CONFIG_ENABLE_MSVC_LEVEL4_WARNINGS=1 -DGLEW_STATIC -DIMGUI_DISABLE_OBSOLETE_FUNCTIONS -DUSE_DL_PREFIX -D_CRT_SECURE_NO_WARNINGS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS

CXX_INCLUDES = @CMakeFiles/PathTracer.dir/includes_CXX.rsp

CXX_FLAGS = -std=gnu++14  -march=native -funroll-loops -mfpmath=sse -msse2 -msse3 -mssse3 -ffast-math -fpermissive  -Wno-format-y2k  -fno-strict-aliasing

