pathtracer -spp 200 -o bedroom.png -s c:\temp\assets-new\assets\bedroom.scene
pathtracer -spp 200 -o bedroom-mirr.png -s c:\msys64\home\user\GLSL-PathTracer-my\assets1\bedroom-mirror.scene
pathtracer -spp 200 -o boy.png -s c:\temp\assets-new\assets\boy.scene
pathtracer -spp 200 -o boyglass.png -s c:\msys64\home\user\GLSL-PathTracer-my\assets1\boyGlass.scene
pathtracer -spp 200 -o coffee_maker.png -s c:\temp\assets-new\assets\coffee_maker.scene
pathtracer -spp 200 -o coffee_cart.png -s c:\temp\assets-new\assets\coffee_cart.scene
pathtracer -spp 200 -o diningroom.png -s c:\temp\assets-new\assets\diningroom.scene
pathtracer -spp 200 -o dragon.png -s c:\temp\assets-new\assets\dragon.scene
pathtracer -spp 200 -o hyperion.png -s ..\assets\hyperion.scene
pathtracer -spp 200 -o hyperion2.png -s ..\assets\hyperion2.scene
pathtracer -spp 200 -o mustang_red.png -s c:\temp\assets-new\assets\mustang_red.scene
pathtracer -spp 200 -o renderman_teapot_all.png -s c:\temp\assets-new\assets\renderman_teapot_all.scene
pathtracer -spp 200 -o spaceship.png -s c:\temp\assets-new\assets\spaceship.scene
pathtracer -spp 200 -o staircase.png -s c:\temp\assets-new\assets\staircase.scene
pathtracer -spp 200 -o stormtrooper.png -s c:\temp\assets-new\assets\stormtrooper.scene